# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudentManagementX9000' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'RealmSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxRealm'
    pod 'ReachabilitySwift'
    pod 'SwiftLint'

  # Pods for StudentManagementX9000

  target 'StudentManagementX9000Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudentManagementX9000UITests' do
    # Pods for testing
  end

end
